name: vacunas_app

services:
  api_vacunas:
    image: api-vacunas-panama:0.0.1
    env_file:
      - ".env"
    #restart: on-failure
    container_name: api_spring_vacunas
    depends_on:
      bd_vacunas:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - network_vacunas

  bd_vacunas:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_vacunas
    ports:
      - "1440:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_PID=Express"
      - "MSSQL_SA_PASSWORD="
    restart: on-failure
    volumes:
      - sql_server_vacunas_data:/var/opt/mssql
      - .\vacunas-init.sql:/vacunas-init.sql
    networks:
      - network_vacunas
    healthcheck:
          test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '' -No -C -Q 'SELECT 1' -b -o /dev/null"]
          interval: 10s
          retries: 10
          start_period: 90s
          timeout: 10s

volumes:
  sql_server_vacunas_data:
    driver: local

networks:
  network_vacunas: